version: "2"
services:

  mongo:
    image: mongo
    volumes:
      - ./dbdata:/data/db
    ports:
      - 8009:27017

  admin:
    image: burgerszoo/node
    volumes:
      - ./apps/admin:/app
    ports:
      - 8002:3000

  ranger:
    image: burgerszoo/node
    volumes:
      - ./apps/ranger:/app
    ports:
      - 8003:3002

  server:
    image: burgerszoo/node
    depends_on:
      - "mongo"
    volumes:
      - ./apps/server:/app
    ports:
      - 8001:3000
