version: "2"
services:

  mongo:
    image: mongo
    volumes:
      - ./dbdata:/data/db
    ports:
      - 8009:27017

  admin:
    image: mastermindzh/generic_node
    volumes:
      - ./apps/admin:/app
    ports:
      - 8001:8080

  ranger:
    image: mastermindzh/generic_node
    volumes:
      - ./apps/ranger:/app
    ports:
      - 8002:8080

  server:
    image: mastermindzh/generic_node
    depends_on:
      - "mongo"
    volumes:
      - ./apps/server:/app
    ports:
      - 8001:8080
