openapi: 3.0.0
info:
  title: Backend
  version: 0.0.1
  description: API beschrijvingen van de gateway en backend.
tags:
  - name: Backend
    description: Alle api calls die bij de backend horen
  - name: Gateway
    description: Alle api calls die bij de gateway horen
paths:
  /pootje:
    post:
      tags:
        - Backend
      summary: Aanmaken van nieuw pootje
      description: >-
        Aanmaken van een nieuw pootje. Response bevat het nieuw aangemaakte poot
        object. 
      deprecated: false
      responses:
        '201':
          description: Nieuwe poot aangemaakt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Poot'
        '500':
          description: Fout bij het aanmaken van een nieuw pootje
  '/pootje/{pootid}/config':
    get:
      tags:
        - Backend
      summary: Opvragen configuratie pootje
      description: Het opvragen van de configuratie van een specifiek pootje
      deprecated: false
      requestBody:
        content:
          string:
            schema:
              type: string
      parameters:
        - in: path
          name: pootid
          schema:
            type: integer
          required: true
          description: 'ID van de poot, waarvan de config wordt opgevraagd'
      responses:
        '200':
          description: De configuratie van de poot
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Config'
        '404':
          description: Configuratie niet gevonden
        '500':
          description: Configuratie kon niet worden opgehaald
  '/pootje/{pootid}/logging':
    post:
      tags:
        - Backend
      summary: Opslaan log data
      description: Verwerken van de logdata die van de pootjes komt.
      deprecated: false
      requestBody:
        content:
          poot:
            schema:
              $ref: '#/components/schemas/Logging'
      parameters:
        - in: path
          name: pootid
          schema:
            type: integer
          required: true
          description: poot id
      responses:
        '201':
          description: Logging opgelsagen
        '404':
          description: Poot kon niet worden gevonden
        '500':
          description: Logging kon niet worden opgeslagen
  '/pootje/{pootid}/scan/':
    post:
      tags:
        - Backend
      summary: Scan data van pootje
      description: Verwerken van de ranger die bij een bepaalde poot komt.
      deprecated: false
      requestBody:
        content:
          pas:
            schema:
              $ref: '#/components/schemas/NFC'
      parameters:
        - in: path
          name: pootid
          schema:
            type: integer
          required: true
          description: ID van de poot die gescand is
      responses:
        '201':
          description: Poot succesvol gescand
        '400':
          description: Ranger bestaat niet
        '404':
          description: Poot kan niet gevonden worden
        '500':
          description: Poot scan niet opgeslagen
  '/pootje/{pootid}/update':
    post:
      tags:
        - Gateway
      summary: Zet instellingen van een poot
      description: >-
        Overschrijf de instellingen van een pootje met nieuwe informatie.
        Wanneer de instellingen niet anders zijn dan de instellingen die al
        bekend zijn dan zal de gateway niks versturen naar de poot.
      parameters:
        - name: pootid
          in: path
          required: true
          schema:
            type: string
          description: >-
            Het ID van het pootje waarvan de instellingen ingesteld moeten
            worden
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Config'
      operationId: zet instellingen van een paaltje
      responses:
        '200':
          description: >-
            De instellingen staan goed op de poot. Er wordt geen transactie
            gestart.
        '202':
          description: >-
            De instellingen gaan naar de poot worden verzonden, maar dit kan
            even duren. De backend zal via voortgangs-updates op de hoogte
            worden gehouden van de voortgang. Als de upload faalt dan zal dit
            ook via deze updates worden gegeven
        '404':
          description: 'De poot bestaat niet. '
        '503':
          description: >-
            De poot is op dit moment niet online en er zal niet geprobeerd
            worden om een transactie te starten.
components:
  schemas:
    Config:
      description: Poot configuratie
      properties:
        poot:
          $ref: '#/components/schemas/Poot'
        audio:
          items:
            $ref: '#/components/schemas/Media'
    Media:
      description: Media items
      properties:
        mediaid:
          type: integer
          description: id van audo object
        url:
          type: string
          description: link naar media object
        type:
          type: string
          enum:
            - weetje
            - diergeluid
    Poot:
      description: Poot/paal in de dierentuin
      properties:
        pootid:
          type: integer
          description: id van de paal
    Logging:
      description: Logging data
      properties:
        poot:
          $ref: '#/components/schemas/Poot'
        logValues:
          items:
            $ref: '#/components/schemas/LogValue'
        timestamp:
          type: string
          format: timestamp
          description: Timestamp of the loggin values
    LogValue:
      description: Gemeten log values inclusief welke sensor gemeten is
      properties:
        name:
          type: string
          description: 'log value type, beschrijft welke sensor gemeten is.'
        value:
          type: string
          description: 'Log value, bevat de gemeten waardes'
    NFC:
      description: Ranger NFC kaart
      properties:
        pasid:
          type: integer
          description: id van de ranger

