version: "2"
services:

  mongo:
    image: mongo
    volumes:
      - ../../dbdata:/data/db
    ports:
      - 8019:27017

  admin:
    image: burgerszoo/prod
    volumes:
      - ../../apps/admin:/app
    ports:
      - 8012:4000

  ranger:
    image: burgerszoo/prod
    volumes:
      - ../../apps/ranger:/app
    ports:
      - 8013:4000

  server:
    image: burgerszoo/node
    depends_on:
      - "mongo"
    volumes:
      - ../../apps/server:/app
    ports:
      - 8011:3000
